### ISSUE TITLE
Installer hexo-seo error and protocol package git is using ssh

### ISSUE THREAD

**Issue by wangshuai-007** [dimaslanjaka/hexo-seo#23]

**Comment by wangshuai-007** [comment]
```bash
npm ERR! code 128
npm ERR! A git connection error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/kevva/url-regex.git
npm ERR! fatal: unable to access 'https://github.com/kevva/url-regex.git/': Failed to connect to github.com port 443 after 21121 ms: Timed out

npm ERR! A complete log of this run can be found in:
```

the log file is like this
```bash
......
2875 timing idealTree:fixDepFlags Completed in 71ms
2876 timing idealTree Completed in 541736ms
2877 timing command:i Completed in 541758ms
2878 verbose stack Error: A git connection error occurred
2878 verbose stack     at makeError (C:\Users\xxx\AppData\Roaming\nvm\v18.10.0\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:24:13)
2878 verbose stack     at C:\Users\xxx\AppData\Roaming\nvm\v18.10.0\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
2878 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2879 verbose cwd D:\学习\Hexo\xxxx-blog
2880 verbose Windows_NT 10.0.19044
2881 verbose node v18.10.0
2882 verbose npm  v8.19.2
2883 error code 128
2884 error A git connection error occurred
2885 error command git --no-replace-objects ls-remote ssh://git@github.com/kevva/url-regex.git
2886 error fatal: unable to access 'https://github.com/kevva/url-regex.git/': Failed to connect to github.com port 443 after 21121 ms: Timed out
2887 verbose exit 128
2888 timing npm Completed in 542178ms
2889 verbose unfinished npm timer reify 1665471408891
2890 verbose unfinished npm timer reify:loadTrees 1665471408908
2891 verbose code 128
2892 error A complete log of this run can be found in:
2892 error     C:\Users\xxx\AppData\Local\npm-cache\_logs\2022-10-11T06_56_48_486Z-debug-0.log
```

can you change `ssh` to `http` in your extension?

**Comment by dimaslanjaka** [comment]
i will fix it soon

**Comment by dimaslanjaka** [comment]
- fixed installer error
- using https protocol instead github:
Test result : 
- https://github.com/dimaslanjaka/hexo-seo/actions/runs/3239691402
- https://github.com/dimaslanjaka/hexo-seo/actions/runs/3239691401

if you still troubled on github protocol, you can overriden it with
```bash
git config --global url."https://github".insteadOf ssh://git@github
```
above command should overriden global config to using https protocol first before ssh

**Comment by wangshuai-007** [comment]
I am in China, It is not easy connect to github and npm registry.

for the command:

`git config --global url."https://github".insteadOf ssh://git@github` 
and 
`npm config set registry https://registry.npm.taobao.org
`
I still got erro :
`fatal: unable to access 'https://github.com/kevva/decompress.git/': OpenSSL SSL_read: Connection was reset, errno 10054`

So ,I try 
Use TUN Mode for clash.

Now ,I can install success.

**Comment by dimaslanjaka** [comment]
You can download master branch of this repo, then place it to folder ex `packages/hexo-seo`, then you can install with `npm i file:./packages/hexo-seo` for offline usage

**Comment by dimaslanjaka** [comment]
now were using static tarball. no more github ssh conflict.

![gambar](https://user-images.githubusercontent.com/12471057/208846730-e548fa74-592f-429e-b462-7b3b652fe0e8.png)

**Comment by dimaslanjaka** [comment]
for now you can pass "resolutions" when using `yarn`.

download all tarballs of non-npm path, then put them into folder (let say foldername "packages").

package.json looks like below

```json
{
  "resolutions": {
    "hexo-seo": "file:./packages/hexo-seo.tgz",
    "another-module": "file:./packages/another-module-tarball.tgz"
  }
}
```

then install using `yarn install`.

all submodules of your dependencies will follows resolutions version range.
