### ISSUE TITLE
Integrate content search and feed

### ISSUE THREAD

**Issue by lopins** [dimaslanjaka/hexo-seo#272]

**Comment by dimaslanjaka** [comment]
describe more

**Comment by lopins** [comment]
> describe more

search:
---
hexo-generator-searchdb
hexo-algolia

rss:
---
hexo-generator-feed

**Comment by dimaslanjaka** [comment]
> > describe more
> 
> ## search:
> 
> hexo-generator-searchdb hexo-algolia
> ## rss:
> 
> hexo-generator-feed

So you need data of all posts including title, description, tags, categories, thumbnail into json data ?
so you can fetch it using ajax/fetch then populate into div ?

**Comment by dimaslanjaka** [comment]
@lopins try this

```bash
npm i hexo-seo@https://github.com/dimaslanjaka/hexo-seo/raw/32c6a21/release/hexo-seo.tgz
```

then run

```bash
hexo seo-search
```

to generate search data.

see documentation https://github.com/dimaslanjaka/hexo-seo/tree/pre-release?tab=readme-ov-file#usage

**Comment by lopins** [comment]
> @lopins try this
> 
> ```bash
> npm i hexo-seo@https://github.com/dimaslanjaka/hexo-seo/raw/32c6a21/release/hexo-seo.tgz
> ```
> 
> then run
> 
> ```bash
> hexo seo-search
> ```
> 
> to generate search data.
> 
> see documentation https://github.com/dimaslanjaka/hexo-seo/tree/pre-release?tab=readme-ov-file#usage

perfect！！！

**Comment by dimaslanjaka** [comment]
still looking perfect method to generate feeds  and atom, ill tell you here

**Comment by dimaslanjaka** [comment]
feeds (rss/atom) generator use `hexo seo-feed`
