### ISSUE TITLE
@UUID and @requests is now updated, considering update?

### ISSUE THREAD

**Issue by blainehuang1028** [dimaslanjaka/hexo-seo#60]
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by dimaslanjaka** [comment]
fixed at https://github.com/dimaslanjaka/hexo-seo/commit/612be9b6a323c86fcf5ed6fd553867275deaeea1
